esphome:
  name: levoit-lv131s

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Levoit-Lv131S Fallback Hotspot"
    password: "OMgo8F13ZBYn"

captive_portal:


spi:
    clk_pin: GPIO21
    miso_pin: GPIO22
    interface: hardware

spi_device:
    id: spidev
    cs_pin: GPIO23
    data_rate: 500khz
    spi_mode: 0
    bit_order: lsb_first    
interval:
  - interval: 5s
    then:
      - lambda: !lambda |-
          id(spidev).enable();
          id(spidev).write_byte(0x4F);
          id(spidev).disable();
